services:
  vendorservice.webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: vendorservice.webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
  vendorservice.database:
    restart: always
    image: postgres:latest
    container_name: vendorservice.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vendordb
    volumes:
      - ./.containers/vendor-db:/var/lib/postgressql/data
    ports:
      - '5432:5432'
  vendorservice.migrations:
    image: ${DOCKER_REGISTRY-}migrations
    container_name: vendorservice.migrations
    build:
      context: .
      dockerfile: src/Migrations/Dockerfile
    depends_on:
      - vendorservice.database
    environment:
      - ConnectionStrings__Database=Host=vendorservice.database;Database=vendordb;Username=postgres;Password=postgres