on:
  workflow_dispatch:
jobs:
  WebAPI:
    uses: lassejonassen/Github-Pipelines/.github/workflows/aspnetcore-webapi.yml@master
    with:
      pipelineName: VendorService
      containerName: vendorservice
